Exclude PerformanceTests from source build
This addresses the following issue in the PerformanceTests:
src/PerformanceTests/Utilities/Common/CompilationHelper.cs(126,23): error CS0534: 'CompilationHelper.OptionsProvider' does not implement inherited abstract member 'AnalyzerConfigOptionsProvider.GlobalOptions.get'

This is a result of https://github.com/dotnet/roslyn/pull/44875 which introduced the new abstract member.

Since the PerformanceTests are not necessary for source-build they were excluded.